import io
import contextlib
import os
from dotenv import load_dotenv
load_dotenv()  
from openai import OpenAI
import pandas as pd

openai_api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=openai_api_key)

df=pd.read_csv("sample_employee_data.csv")

def run_code(code: str) -> str:
    """
    Executes the given Python code and returns the output as a string.

    Args:
        code (str): The Python code to execute.

    Returns:
        str: The output of the executed code.
    """
    
    try:
        output_buffer = io.StringIO()
        with contextlib.redirect_stdout(output_buffer):
            exec(code,{"pd":pd,"df":df})
        output = output_buffer.getvalue()
    except Exception as e:
        output = f"Error: {e}"
    return output

def data_analysis_agent(messages: list) -> str:
    """
    Uses OpenAI's API to generate a response based on the given prompt.

    Args:
        messages: list: The mesages to send to the OpenAI API.

    Returns:
        str: The response generated by the OpenAI API.
    """
    
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=messages,
        max_tokens=1000
    )
    return response.choices[0].message.content.strip()

user_qt=input("Ask to an agent:")
Message_queue=[
                {
                "role": "system", "content": f"""You are a Python code generator for a data analysis agent.
                RULES:
                - Output ONLY raw, executable Python code. Nothing else.
                - Do NOT include explanations, comments, or any text before or after the code.
                - Do NOT wrap the code in markdown fences (no ``` or ```python).
                - The code MUST print its final result using print(), since only printed output is captured.
                - If a previous attempt returned an error, fix the code and return the corrected version.
                You are analyzing a pandas DataFrame called `df` that is already loaded.
                    Here is its structure:

                    Columns and types:
                    {df.dtypes}

                    First rows:
                    {df.head().to_string()}

                    Write pandas code using the existing `df` to answer the user's question.
                """},
                {"role": "user", "content": user_qt}
            ]
for i in range(0,5):
    code=data_analysis_agent(Message_queue)
    if code.startswith("```python"):
        code=code.split("```python")[1].strip("`")
    elif code.startswith("```"):
        code=code.strip("`")
    result = run_code(code)
    print("epoch",i,"->",result)
    if result.startswith("Error"):
        Message_queue.append({"role":"assistant","content": code})
        Message_queue.append({"role":"user","content": result})
    elif result.strip()=="":
        Message_queue.append({"role":"assistant","content": code})
        Message_queue.append({"role":"user","content": "Code ran but printed nothing — make sure to print() the result."})
    else:
        break

if result.startswith("Error"):
    print("Failure: Couldn Solve the Error:",result)
elif result.strip()=="":
    print("Failure: Coudlnt able to print")

print(result)
